# Generated by Django 4.1.5 on 2023-02-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='next',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Discription', models.TextField()),
            ],
        ),
    ]
